name: Deploy Static Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload static files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: rene
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "*"
          target: "/var/www/renem.me/pokedex-app"
